"""empty message

Revision ID: 491ad26c2415
Revises: ac4d5bdb3b48
Create Date: 2025-05-16 19:28:49.765016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491ad26c2415'
down_revision = 'ac4d5bdb3b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], name='follower_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], name='follower_user_to_id_fkey'),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id', name='follower_pkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
